using Kivra.Application;
using Kivra.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
namespace Kivra.Infrastructure;
public sealed class PrinterOperations(KivraDbContext db, IEnumerable<ILabelPrinter> printers, ITsplGenerator tspl, TimeZoneInfo tz) {
 ILabelPrinter Resolve(Printer p)=>printers.FirstOrDefault(x=>p.Driver switch{"TscTsplNetwork"=>x is TscTsplNetworkPrinter,"TscTsplUsb"=>x is TscTsplUsbPrinter,"EpsonEscPosUsb"=>x is EpsonEscPosUsbPrinter,_=>x is FakeLabelPrinter})??throw new InvalidOperationException($"Printer driver '{p.Driver}' is not registered.");
 public Task<PrinterResult> TestAsync(Guid printerId,CancellationToken ct) => TestCore(printerId,ct);
 async Task<PrinterResult> TestCore(Guid id,CancellationToken ct) { var p=await db.Printers.FindAsync([id],ct)??throw new KeyNotFoundException("Printer not found."); if(RequiresBridge(p)){var platform=p.Driver=="AndroidBridge"?"android":"windows";var online=await BridgeOnline(platform,ct);return online?new(true):new(false,$"No {PlatformName(platform)} Print Bridge is online. Open the bridge app on the printer device and keep it running.");}return await Resolve(p).TestConnectionAsync(p,ct); }
 public async Task<PrinterResult> TestPrintAsync(Guid printerId,Guid userId,CancellationToken ct) { var p=await db.Printers.FindAsync([printerId],ct)??throw new KeyNotFoundException("Printer not found.");if(RequiresBridge(p)){var platform=p.Driver=="AndroidBridge"?"android":"windows";if(!await BridgeOnline(platform,ct))return new(false,$"No {PlatformName(platform)} Print Bridge is online. Open the bridge app on the printer device and keep it running.");var now=DateTimeOffset.UtcNow;var sample=new Label { LabelCode=$"TEST-{now:yyMMddHHmmss}-{Guid.NewGuid():N}"[..25],ItemNameSnapshot="KIVRA TEST LABEL",CategorySnapshot="System",ClassificationSnapshot=Classification.NotApplicable,DateTerminologySnapshot="TESTED",OperationalDateTime=now,ExpiryDateTime=now,ShelfLifeRuleSnapshot="Test",StorageLocationSnapshot="PRINTER TEST",CreatedByUserId=userId,PrinterId=p.Id,CurrentStatus=LabelStatus.Cancelled };var job=new PrintJob { Label=sample,PrinterId=p.Id,RequestedByUserId=userId,IdempotencyKey=$"test-{Guid.NewGuid():N}",Status=PrintJobStatus.Queued,Payload=tspl.Generate(sample,p,tz) };db.Add(job);db.Add(new AuditLog { UserId=userId,Action="PrinterTestQueued",EntityName=nameof(Printer),EntityId=p.Id,NewValues=p.Name });await db.SaveChangesAsync(ct);return new(true); }var directSample=new Label { LabelCode="TEST-0001",ItemNameSnapshot="KIVRA TEST LABEL",CategorySnapshot="System",ClassificationSnapshot=Classification.NotApplicable,DateTerminologySnapshot="TESTED",OperationalDateTime=DateTimeOffset.UtcNow,ExpiryDateTime=DateTimeOffset.UtcNow,ShelfLifeRuleSnapshot="Test",StorageLocationSnapshot="PRINTER TEST" };return await Resolve(p).PrintAsync(p,tspl.Generate(directSample,p,tz),ct); }
 bool RequiresBridge(Printer p)=>p.Driver=="AndroidBridge"||(!OperatingSystem.IsWindows()&&p.Driver is "TscTsplUsb" or "EpsonEscPosUsb");
 Task<bool> BridgeOnline(string platform,CancellationToken ct)=>db.BridgeDevices.AnyAsync(x=>x.Active&&x.RevokedAt==null&&x.Platform!=null&&x.Platform.ToLower()==platform&&x.LastSeenAt>DateTimeOffset.UtcNow.AddMinutes(-1),ct);
 static string PlatformName(string platform)=>platform=="windows"?"Windows":"Android";
}
public sealed class ExpiryNotificationWorker(IServiceScopeFactory scopes, ILogger<ExpiryNotificationWorker> log) : BackgroundService {
 protected override async Task ExecuteAsync(CancellationToken stoppingToken) { while(!stoppingToken.IsCancellationRequested) { try { await Process(stoppingToken); } catch(Exception ex) { log.LogError(ex,"Expiry processing failed"); } await Task.Delay(TimeSpan.FromMinutes(5),stoppingToken); } }
 async Task Process(CancellationToken ct) { using var scope=scopes.CreateScope(); var db=scope.ServiceProvider.GetRequiredService<KivraDbContext>(); var now=DateTimeOffset.UtcNow; var active=await db.Labels.Where(x=>x.CurrentStatus==LabelStatus.Active).ToListAsync(ct); var expired=active.Where(x=>x.ExpiryDateTime<=now).ToList(); foreach(var label in expired) { label.CurrentStatus=LabelStatus.Expired; db.Notifications.Add(new Notification { Type="Expired",Title="Item expired",Message=$"{label.ItemNameSnapshot} ({label.LabelCode}) is expired.",LabelId=label.Id }); db.AuditLogs.Add(new AuditLog { Action="LabelExpired",EntityName="Label",EntityId=label.Id }); } if(expired.Count>0)await db.SaveChangesAsync(ct); }
}
