<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net9.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="../Kivra.Application/Kivra.Application.csproj" /><ProjectReference Include="../Kivra.Infrastructure/Kivra.Infrastructure.csproj" /></ItemGroup></Project>
