using Kivra.Application;
using Kivra.Api;
using Kivra.Domain;
using Kivra.Infrastructure;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.RateLimiting;
using System.Security.Claims;
using System.Text.Json.Serialization;
using System.Threading.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
var builder = WebApplication.CreateBuilder(args);
var provider = builder.Configuration["Database:Provider"];
if (string.IsNullOrWhiteSpace(provider))
    throw new InvalidOperationException("Database:Provider must be configured.");
var connectionString = builder.Configuration.GetConnectionString("Default");
if (string.IsNullOrWhiteSpace(connectionString))
    throw new InvalidOperationException("ConnectionStrings:Default must be configured.");
var adminPin = builder.Configuration["Bootstrap:AdminPin"];
if (string.IsNullOrWhiteSpace(adminPin))
    throw new InvalidOperationException("Bootstrap:AdminPin must be configured for the initial administrator account.");
builder.Services.AddDbContext<KivraDbContext>(o =>
{
    if (provider.Equals("Postgres", StringComparison.OrdinalIgnoreCase))
        o.UseNpgsql(connectionString, npgsql => npgsql.EnableRetryOnFailure())
            .ConfigureWarnings(warnings => warnings.Ignore(RelationalEventId.PendingModelChangesWarning));
    else if (provider.Equals("Sqlite", StringComparison.OrdinalIgnoreCase))
        o.UseSqlite(connectionString);
    else
        throw new InvalidOperationException("Database:Provider must be Postgres or Sqlite.");
});
builder.Services.ConfigureHttpJsonOptions(o=>o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));
builder.Services.AddRateLimiter(options => options.AddFixedWindowLimiter("login", limiter =>
{
    limiter.PermitLimit = 20;
    limiter.Window = TimeSpan.FromMinutes(1);
    limiter.QueueLimit = 0;
    limiter.AutoReplenishment = true;
}));
builder.Services.AddSingleton(TimeZoneInfo.FindSystemTimeZoneById("Asia/Kolkata")); builder.Services.AddScoped<IExpiryCalculator, ExpiryCalculator>(); builder.Services.AddSingleton<ILabelCodeGenerator, LabelCodeGenerator>(); builder.Services.AddSingleton<ITsplGenerator, TsplGenerator>(); builder.Services.AddSingleton<UsbPrinterCatalog>(); builder.Services.AddSingleton<ILabelPrinter, FakeLabelPrinter>(); builder.Services.AddSingleton<ILabelPrinter, TscTsplNetworkPrinter>(); builder.Services.AddSingleton<ILabelPrinter,TscTsplUsbPrinter>(); builder.Services.AddSingleton<ILabelPrinter,EpsonEscPosUsbPrinter>(); builder.Services.AddScoped<LabelPrintService>(); builder.Services.AddProblemDetails();
builder.Services.AddDataProtection(); builder.Services.AddScoped<IPinAuthentication,PinAuthentication>(); builder.Services.AddScoped<PrinterOperations>(); builder.Services.AddSingleton<PrinterDiscoveryService>(); builder.Services.AddHostedService<ExpiryNotificationWorker>(); builder.Services.AddAuthentication("Kivra").AddScheme<AuthenticationSchemeOptions,KivraAuthenticationHandler>("Kivra",null); builder.Services.AddAuthorization(o=> { o.FallbackPolicy=new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build(); o.AddPolicy("Staff",p=>p.RequireRole(nameof(UserRole.KitchenStaff),nameof(UserRole.Supervisor),nameof(UserRole.Administrator))); o.AddPolicy("Supervisor",p=>p.RequireRole(nameof(UserRole.Supervisor),nameof(UserRole.Administrator))); o.AddPolicy("Admin",p=>p.RequireRole(nameof(UserRole.Administrator))); });
var app = builder.Build(); app.UseExceptionHandler(); app.UseDefaultFiles(); app.UseStaticFiles(); app.UseRateLimiter(); app.UseAuthentication(); app.UseAuthorization();
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<KivraDbContext>();
    if (db.Database.IsNpgsql())
        await db.Database.MigrateAsync();
    else
    {
        await db.Database.EnsureCreatedAsync();
        await SchemaCompatibility.EnsureAsync(db);
    }
    await SeedData.EnsureSeededAsync(db, adminPin);
}
app.MapPost("/api/auth/pin", async (PinLoginRequest request, IPinAuthentication auth, CancellationToken ct) => { var user=await auth.AuthenticateAsync(request.Pin,ct); return user is null ? Results.Unauthorized() : Results.Ok(new { token=auth.IssueToken(user),user=new {user.Id,user.DisplayName,user.Role} }); }).RequireRateLimiting("login").AllowAnonymous();
app.MapGet("/api/users", async (KivraDbContext db) => await db.Users.OrderBy(x=>x.DisplayName).Select(x=>new {x.Id,x.DisplayName,x.Role,x.Active,x.CreatedAt}).ToListAsync()).RequireAuthorization("Admin");
app.MapPost("/api/users", async (CreateUserRequest request,KivraDbContext db) => { if(string.IsNullOrWhiteSpace(request.DisplayName)||request.Pin.Length<4)return Results.ValidationProblem(new Dictionary<string,string[]>{{"user",["Name and a PIN of at least four digits are required."]}}); var user=new User { DisplayName=request.DisplayName.Trim(),PinHash=PinAuthentication.Hash(request.Pin),Role=request.Role };db.Add(user);db.Add(new AuditLog { Action="UserCreated",EntityName="User",EntityId=user.Id,NewValues=$"{user.DisplayName}/{user.Role}" });await db.SaveChangesAsync();return Results.Created($"/api/users/{user.Id}",new {user.Id,user.DisplayName,user.Role});}).RequireAuthorization("Admin");
app.MapPatch("/api/users/{id:guid}/active", async(Guid id,SetActiveRequest request,KivraDbContext db)=>{var user=await db.Users.FindAsync(id);if(user is null)return Results.NotFound();user.Active=request.Active;user.UpdatedAt=DateTimeOffset.UtcNow;db.Add(new AuditLog {Action=request.Active?"UserActivated":"UserDeactivated",EntityName="User",EntityId=id});await db.SaveChangesAsync();return Results.NoContent();}).RequireAuthorization("Admin");
app.MapPut("/api/users/{id:guid}/pin", async(Guid id,SetPinRequest request,KivraDbContext db)=>{if(request.Pin.Length<4)return Results.ValidationProblem(new Dictionary<string,string[]>{{"pin",["PIN must contain at least four characters."]}});var user=await db.Users.FindAsync(id);if(user is null)return Results.NotFound();user.PinHash=PinAuthentication.Hash(request.Pin);user.UpdatedAt=DateTimeOffset.UtcNow;db.Add(new AuditLog {Action="UserPinChanged",EntityName="User",EntityId=id});await db.SaveChangesAsync();return Results.NoContent();}).RequireAuthorization("Admin");
app.MapGet("/api/items", async (KivraDbContext db) => await db.Items.Include(x=>x.Category).Include(x=>x.DefaultStorageLocation).Where(x=>x.Active).OrderBy(x=>x.Name).Select(x=>new { x.Id,x.Name,x.ShortName,x.ImageDataUrl,x.CategoryId,x.Classification,x.LabelType,x.DateTerminology,x.ShelfLifeValue,x.ShelfLifeUnit,x.DefaultStorageLocationId,x.DefaultLabelTemplate,x.Active, Category=x.Category!.Name, Storage=x.DefaultStorageLocation!=null?x.DefaultStorageLocation.Name:null }).ToListAsync()).RequireAuthorization("Staff");
app.MapGet("/api/printers", async (KivraDbContext db) => await db.Printers.Where(x=>x.Enabled).ToListAsync()).RequireAuthorization("Staff");
app.MapGet("/api/printers/all", async (KivraDbContext db) => await db.Printers.OrderBy(x=>x.Name).ToListAsync()).RequireAuthorization("Admin");
app.MapPost("/api/printers", async (Printer printer,ClaimsPrincipal user,KivraDbContext db) => { var errors=ValidatePrinter(printer);if(errors is not null)return Results.ValidationProblem(errors); printer.Id=Guid.NewGuid();printer.CreatedAt=printer.UpdatedAt=DateTimeOffset.UtcNow; db.Add(printer); db.Add(new AuditLog {UserId=Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!),Action="PrinterCreated",EntityName="Printer",EntityId=printer.Id,NewValues=$"{printer.Name}/{printer.Driver}/{printer.IpAddress}:{printer.TcpPort}" }); await db.SaveChangesAsync(); return Results.Created($"/api/printers/{printer.Id}",printer); }).RequireAuthorization("Admin");
app.MapPut("/api/printers/{id:guid}", async(Guid id,Printer input,ClaimsPrincipal user,KivraDbContext db)=>{var errors=ValidatePrinter(input);if(errors is not null)return Results.ValidationProblem(errors);var printer=await db.Printers.FindAsync(id);if(printer is null)return Results.NotFound();var previous=$"{printer.Name}/{printer.Driver}/{printer.IpAddress}:{printer.TcpPort}/{printer.UsbQueueName}/{printer.Dpi}/{printer.LabelWidthMm}x{printer.LabelHeightMm}/{printer.MediaSensingMode}/{printer.GapMm}/{printer.Enabled}";printer.Name=input.Name.Trim();printer.Model=input.Model.Trim();printer.Driver=input.Driver;printer.IpAddress=input.IpAddress.Trim();printer.TcpPort=input.TcpPort;printer.UsbQueueName=input.UsbQueueName?.Trim();printer.Dpi=input.Dpi;printer.LabelWidthMm=input.LabelWidthMm;printer.LabelHeightMm=input.LabelHeightMm;printer.MediaSensingMode=input.MediaSensingMode;printer.GapMm=input.GapMm;printer.PrintMethod=input.PrintMethod;printer.PrintSpeedIps=input.PrintSpeedIps;printer.PrintDensity=input.PrintDensity;printer.Enabled=input.Enabled;printer.UpdatedAt=DateTimeOffset.UtcNow;db.Add(new AuditLog{UserId=Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!),Action="PrinterSettingsChanged",EntityName="Printer",EntityId=id,PreviousValues=previous,NewValues=$"{printer.Name}/{printer.Driver}/{printer.IpAddress}:{printer.TcpPort}/{printer.UsbQueueName}/{printer.Dpi}/{printer.LabelWidthMm}x{printer.LabelHeightMm}/{printer.MediaSensingMode}/{printer.GapMm}/{printer.Enabled}"});await db.SaveChangesAsync();return Results.Ok(printer);}).RequireAuthorization("Admin");
app.MapPost("/api/printers/{id:guid}/test-connection", async (Guid id, PrinterOperations ops, CancellationToken ct) => Results.Ok(await ops.TestAsync(id,ct))).RequireAuthorization("Admin");
app.MapPost("/api/printers/{id:guid}/test-print", async (Guid id, PrinterOperations ops, CancellationToken ct) => Results.Ok(await ops.TestPrintAsync(id,ct))).RequireAuthorization("Admin");
app.MapGet("/api/printers/discover",async(int? port,HttpContext http,PrinterDiscoveryService discovery,CancellationToken ct)=>Results.Ok(await discovery.DiscoverAsync(port??9100,http.Connection.RemoteIpAddress,ct))).RequireAuthorization("Admin");
app.MapGet("/api/printers/discover-usb",async(UsbPrinterCatalog catalog,CancellationToken ct)=>Results.Ok(new{queues=await catalog.GetQueuesAsync(ct)})).RequireAuthorization("Admin");
app.MapGet("/api/categories", async (KivraDbContext db) => await db.Categories.Where(x=>x.Active).OrderBy(x=>x.Name).ToListAsync()).RequireAuthorization("Staff");
app.MapGet("/api/storage-locations", async (KivraDbContext db) => await db.StorageLocations.Where(x=>x.Active).OrderBy(x=>x.Name).ToListAsync()).RequireAuthorization("Staff");
app.MapGet("/api/storage-locations/all", async (KivraDbContext db) => await db.StorageLocations.OrderBy(x=>x.Name).ToListAsync()).RequireAuthorization("Admin");
app.MapPost("/api/categories", async (Category input, KivraDbContext db) => { input.Id=Guid.NewGuid(); input.CreatedAt=input.UpdatedAt=DateTimeOffset.UtcNow; db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/categories/{input.Id}",input); }).RequireAuthorization("Admin");
app.MapPost("/api/storage-locations", async (StorageLocation input, KivraDbContext db) => { input.Id=Guid.NewGuid(); input.CreatedAt=input.UpdatedAt=DateTimeOffset.UtcNow; db.Add(input); await db.SaveChangesAsync(); return Results.Created($"/api/storage-locations/{input.Id}",input); }).RequireAuthorization("Admin");
app.MapPatch("/api/storage-locations/{id:guid}/active", async(Guid id,SetActiveRequest request,ClaimsPrincipal user,KivraDbContext db)=>{var location=await db.StorageLocations.FindAsync(id);if(location is null)return Results.NotFound();location.Active=request.Active;location.UpdatedAt=DateTimeOffset.UtcNow;db.Add(new AuditLog {UserId=Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!),Action=request.Active?"StorageLocationEnabled":"StorageLocationDisabled",EntityName=nameof(StorageLocation),EntityId=id,NewValues=location.Name});await db.SaveChangesAsync();return Results.NoContent();}).RequireAuthorization("Admin");
app.MapPost("/api/items", async (Item input,ClaimsPrincipal user,KivraDbContext db) => { if(input.ShelfLifeValue<1 || string.IsNullOrWhiteSpace(input.Name)) return Results.ValidationProblem(new Dictionary<string,string[]>{{"item",["Name and a shelf life greater than zero are required."]}}); input.Id=Guid.NewGuid(); input.Name=input.Name.Trim();input.CreatedAt=input.UpdatedAt=DateTimeOffset.UtcNow; db.Add(input); db.Add(new AuditLog {UserId=Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!),Action="ItemCreated",EntityName="Item",EntityId=input.Id,NewValues=$"{input.Name}/{input.DateTerminology}/{input.ShelfLifeValue} {input.ShelfLifeUnit}"}); await db.SaveChangesAsync(); return Results.Created($"/api/items/{input.Id}",input); }).RequireAuthorization("Admin");
app.MapPut("/api/items/{id:guid}", async(Guid id,Item input,ClaimsPrincipal user,KivraDbContext db)=>{if(input.ShelfLifeValue<1||string.IsNullOrWhiteSpace(input.Name))return Results.ValidationProblem(new Dictionary<string,string[]>{{"item",["Name and a shelf life greater than zero are required."]}});var item=await db.Items.FindAsync(id);if(item is null)return Results.NotFound();if(!await db.Categories.AnyAsync(x=>x.Id==input.CategoryId&&x.Active))return Results.ValidationProblem(new Dictionary<string,string[]>{{"categoryId",["Select an active category."]}});if(input.DefaultStorageLocationId.HasValue&&!await db.StorageLocations.AnyAsync(x=>x.Id==input.DefaultStorageLocationId&&x.Active))return Results.ValidationProblem(new Dictionary<string,string[]>{{"defaultStorageLocationId",["Select an active storage location."]}});var previous=$"{item.Name}/{item.DateTerminology}/{item.ShelfLifeValue} {item.ShelfLifeUnit}/{item.DefaultStorageLocationId}";item.Name=input.Name.Trim();item.ShortName=input.ShortName?.Trim();item.ImageDataUrl=input.ImageDataUrl;item.CategoryId=input.CategoryId;item.Classification=input.Classification;item.LabelType=input.LabelType;item.DateTerminology=input.DateTerminology.Trim();item.ShelfLifeValue=input.ShelfLifeValue;item.ShelfLifeUnit=input.ShelfLifeUnit;item.DefaultStorageLocationId=input.DefaultStorageLocationId;item.DefaultLabelTemplate=input.DefaultLabelTemplate;item.Active=input.Active;item.UpdatedAt=DateTimeOffset.UtcNow;db.Add(new AuditLog{UserId=Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!),Action="ItemShelfLifeChanged",EntityName="Item",EntityId=id,PreviousValues=previous,NewValues=$"{item.Name}/{item.DateTerminology}/{item.ShelfLifeValue} {item.ShelfLifeUnit}/{item.DefaultStorageLocationId}"});await db.SaveChangesAsync();return Results.Ok(item);}).RequireAuthorization("Admin");
app.MapPost("/api/labels/print", async (PrintLabelRequest request, ClaimsPrincipal user, LabelPrintService service, CancellationToken ct) => { var userId=Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!); return Results.Ok(await service.PrintAsync(request with { RequestedByUserId=userId },ct)); }).RequireAuthorization("Staff");
app.MapPost("/api/labels/{id:guid}/reprint", async (Guid id, ReprintRequest request, ClaimsPrincipal user, LabelPrintService service, CancellationToken ct) => Results.Ok(await service.ReprintAsync(id,Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!),request.IdempotencyKey,ct))).RequireAuthorization("Supervisor");
app.MapGet("/api/labels/{id:guid}/preview.tspl", async (Guid id,KivraDbContext db,ITsplGenerator generator,TimeZoneInfo zone,CancellationToken ct)=> { var label=await db.Labels.FindAsync([id],ct);if(label is null)return Results.NotFound();var printer=await db.Printers.FindAsync([label.PrinterId],ct);if(printer is null)return Results.NotFound();return Results.Text(generator.Generate(label,printer,zone),"text/plain");}).RequireAuthorization("Supervisor");
app.MapGet("/api/labels", async (KivraDbContext db) => { var labels=await db.Labels.Include(x=>x.PrintJobs).ToListAsync();return labels.OrderByDescending(x=>x.CreatedAt).Select(x=>new LabelHistoryDto(x.Id,x.LabelCode,x.ItemNameSnapshot,x.OperationalDateTime,x.ExpiryDateTime,x.StorageLocationSnapshot,x.CurrentStatus,x.SuccessfulPrintCount,x.PrintJobs.OrderByDescending(j=>j.RequestedAt).Select(j=>(PrintJobStatus?)j.Status).FirstOrDefault())); });
app.MapPatch("/api/labels/{id:guid}/status", async (Guid id, ChangeStatusRequest request,ClaimsPrincipal user,KivraDbContext db) => { var label=await db.Labels.FindAsync(id); if(label is null)return Results.NotFound(); if(label.CurrentStatus is LabelStatus.Cancelled or LabelStatus.Consumed)return Results.BadRequest("Terminal labels cannot be changed."); var old=label.CurrentStatus; label.CurrentStatus=request.Status; label.UpdatedAt=DateTimeOffset.UtcNow; db.Add(new AuditLog { UserId=Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!),Action=$"Label{request.Status}",EntityName="Label",EntityId=id,PreviousValues=old.ToString(),NewValues=request.Status.ToString() }); await db.SaveChangesAsync(); return Results.Ok(); }).RequireAuthorization("Supervisor");
app.MapGet("/api/expiry", async (string? window, KivraDbContext db) => { var now=DateTimeOffset.UtcNow; var midnight=new DateTimeOffset(now.Year,now.Month,now.Day,0,0,0,TimeSpan.Zero); var until=window?.ToLowerInvariant() switch { "today"=>midnight.AddDays(1), "tomorrow"=>midnight.AddDays(2), "3days"=>midnight.AddDays(3), "7days"=>midnight.AddDays(7), _=>DateTimeOffset.MaxValue }; var active=await db.Labels.Where(x=>x.CurrentStatus==LabelStatus.Active).ToListAsync(); return active.Where(x=>x.ExpiryDateTime<=until).OrderBy(x=>x.ExpiryDateTime).Select(x=>new {x.Id,x.ItemNameSnapshot,x.LabelCode,x.OperationalDateTime,x.ExpiryDateTime,x.StorageLocationSnapshot,x.CurrentStatus}); });
app.MapGet("/api/print-jobs", async (KivraDbContext db) => (await db.PrintJobs.ToListAsync()).OrderByDescending(x=>x.RequestedAt).Take(200)).RequireAuthorization("Supervisor");
app.MapPost("/api/print-jobs/{id:guid}/retry", async(Guid id,ClaimsPrincipal user,LabelPrintService printer,KivraDbContext db,CancellationToken ct)=> { var job=await db.PrintJobs.FindAsync([id],ct);if(job is null)return Results.NotFound();if(job.Status is not PrintJobStatus.Failed)return Results.BadRequest("Only failed print jobs can be retried.");return Results.Ok(await printer.ReprintAsync(job.LabelId,Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!),Guid.NewGuid().ToString("N"),ct));}).RequireAuthorization("Supervisor");
app.MapGet("/api/notifications", async (KivraDbContext db) => (await db.Notifications.Where(x=>x.ReadAt==null).ToListAsync()).OrderByDescending(x=>x.CreatedAt).Take(100)).RequireAuthorization("Staff");
app.MapPost("/api/notifications/{id:guid}/read", async(Guid id,KivraDbContext db) => {var n=await db.Notifications.FindAsync(id);if(n is null)return Results.NotFound();n.ReadAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return Results.NoContent();}).RequireAuthorization("Staff");
app.MapGet("/api/reports/labels.csv", async (KivraDbContext db) => { var records=(await db.Labels.ToListAsync()).OrderByDescending(x=>x.CreatedAt); var csv="Label Code,Item,Created,Expiry,Storage,Status\n"+string.Join('\n',records.Select(x=>$"{x.LabelCode},\"{x.ItemNameSnapshot.Replace("\"","\"\"")}\",{x.CreatedAt:O},{x.ExpiryDateTime:O},\"{x.StorageLocationSnapshot}\",{x.CurrentStatus}")); return Results.File(System.Text.Encoding.UTF8.GetBytes(csv),"text/csv","kivra-label-report.csv"); }).RequireAuthorization("Supervisor");
app.MapGet("/api/dashboard", async (KivraDbContext db) => { var now=DateTimeOffset.UtcNow; var midnight=new DateTimeOffset(now.Year,now.Month,now.Day,0,0,0,TimeSpan.Zero); var labels=await db.Labels.ToListAsync();var jobs=await db.PrintJobs.ToListAsync(); return new { labelsPrintedToday=jobs.Count(x=>x.Status==PrintJobStatus.Printed && x.CompletedAt>=midnight), currentlyActive=labels.Count(x=>x.CurrentStatus==LabelStatus.Active), expired=labels.Count(x=>x.ExpiryDateTime<now && x.CurrentStatus==LabelStatus.Active), expiringToday=labels.Count(x=>x.CurrentStatus==LabelStatus.Active && x.ExpiryDateTime>=now && x.ExpiryDateTime<midnight.AddDays(1)), printerFailures=jobs.Count(x=>x.Status==PrintJobStatus.Failed) }; });
static Dictionary<string,string[]>? ValidatePrinter(Printer p){var errors=new Dictionary<string,string[]>();if(string.IsNullOrWhiteSpace(p.Name))errors["name"]=["Printer name is required."];if(string.IsNullOrWhiteSpace(p.Model))errors["model"]=["Printer model is required."];if(p.Driver is not ("Fake" or "TscTsplNetwork" or "TscTsplUsb" or "EpsonEscPosUsb"))errors["driver"]=["Driver must be Fake, TscTsplNetwork, TscTsplUsb, or EpsonEscPosUsb."];if(p.Driver=="TscTsplNetwork"&&string.IsNullOrWhiteSpace(p.IpAddress))errors["ipAddress"]=["IP address is required for a network printer."];if(p.Driver is "TscTsplUsb" or "EpsonEscPosUsb"&&string.IsNullOrWhiteSpace(p.UsbQueueName))errors["usbQueueName"]=["An operating-system USB printer queue is required."];if(p.Driver=="TscTsplNetwork"&&p.TcpPort is <1 or >65535)errors["tcpPort"]=["TCP port must be between 1 and 65535."];if(p.Dpi is not (203 or 300))errors["dpi"]=["TSC resolution must be 203 or 300 DPI."];if(p.Model.Contains("TE210",StringComparison.OrdinalIgnoreCase)&&p.Dpi!=203)errors["dpi"]=["TSC TE210 has a fixed 203 DPI print head."];if((p.Model.Contains("TE300",StringComparison.OrdinalIgnoreCase)||p.Model.Contains("TE310",StringComparison.OrdinalIgnoreCase))&&p.Dpi!=300)errors["dpi"]=["TSC TE300/TE310 models have a fixed 300 DPI print head."];var maxWidth=p.Dpi==300?105.7m:108m;if(p.LabelWidthMm<20||p.LabelWidthMm>maxWidth||p.LabelHeightMm<10)errors["labelSize"]=[$"Label size must be at least 20 × 10 mm and width cannot exceed {maxWidth} mm at {p.Dpi} DPI."];if(p.MediaSensingMode is not ("Gap" or "BlackMark" or "Continuous"))errors["mediaSensingMode"]=["Media sensing must be Gap, BlackMark, or Continuous."];if(p.MediaSensingMode!="Continuous"&&p.GapMm<=0)errors["gapMm"]=["Gap or black-mark size must be greater than zero."];if(p.PrintMethod is not ("DirectThermal" or "ThermalTransfer"))errors["printMethod"]=["Print method must be DirectThermal or ThermalTransfer."];var maxSpeed=p.Dpi==300?5m:6m;if(p.PrintSpeedIps<1||p.PrintSpeedIps>maxSpeed)errors["printSpeedIps"]=[$"Print speed must be between 1 and {maxSpeed} inches per second at {p.Dpi} DPI."];if(p.PrintDensity is <0 or >15)errors["printDensity"]=["Print density must be between 0 and 15."];return errors.Count==0?null:errors;}
app.Run();
public record PinLoginRequest(string Pin);
public record ReprintRequest(string IdempotencyKey);
public record ChangeStatusRequest(LabelStatus Status);
public record CreateUserRequest(string DisplayName, string Pin, UserRole Role);
public record SetActiveRequest(bool Active);
public record SetPinRequest(string Pin);
